// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(47,20,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(9,77,2^(32.598148))
// 
// Ring
// degree d = 64
// modulus q = 18889465931478580855981, log(q) ~ 74.0
// factors q = q1
// 
// Compression
// D = 9
// gamma = 231388, log(gamma) ~ 17.819955
// 
// Dimensions of secrets
// s1: m1 = 10
// m: l = 0
// s2: m2 = 67
// 
// Size of secrets
// l2(s1) <= alpha = 49.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 6)
// exact euclidean: yes (dimensions: [2, 2], bounds: [4.0, 44.72136])
// approximate infinity: yes (psi: 2148.6388, dimension: 1, bound: 6400.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3174.4, log(stdev3/1.55) = 11.0
// stdev4 = 406323.2, log(stdev4/1.55) = 18.0
// 
// Repetition rate
// M1 = 2.5326351
// M2 = 2.8364453
// M3 = 1.0431783
// M4 = 1.0426968
// total = 7.8138236
// 
// Security
// MSIS dimension: 9
// MSIS root hermite factor: 1.0043295
// MLWE dimension: 47
// MLWE root hermite factor: 1.0043229
// 
// Proof size
// ~ 22.1503906250000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241]
// bit length of products: [49, 99, 149, 199]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893]

#include "lazer.h"
static const limb_t _blind_sig_com_d64_q_limbs[] = {1197UL, 1024UL};
static const int_t _blind_sig_com_d64_q = {{(limb_t *)_blind_sig_com_d64_q_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_qminus1_limbs[] = {1196UL, 1024UL};
static const int_t _blind_sig_com_d64_qminus1 = {{(limb_t *)_blind_sig_com_d64_qminus1_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_m_limbs[] = {81635460488351085UL, 0UL};
static const int_t _blind_sig_com_d64_m = {{(limb_t *)_blind_sig_com_d64_m_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_mby2_limbs[] = {40817730244175542UL, 0UL};
static const int_t _blind_sig_com_d64_mby2 = {{(limb_t *)_blind_sig_com_d64_mby2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_gamma_limbs[] = {231388UL, 0UL};
static const int_t _blind_sig_com_d64_gamma = {{(limb_t *)_blind_sig_com_d64_gamma_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_gammaby2_limbs[] = {115694UL, 0UL};
static const int_t _blind_sig_com_d64_gammaby2 = {{(limb_t *)_blind_sig_com_d64_gammaby2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_pow2D_limbs[] = {512UL, 0UL};
static const int_t _blind_sig_com_d64_pow2D = {{(limb_t *)_blind_sig_com_d64_pow2D_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_pow2Dby2_limbs[] = {256UL, 0UL};
static const int_t _blind_sig_com_d64_pow2Dby2 = {{(limb_t *)_blind_sig_com_d64_pow2Dby2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Bsq_limbs[] = {17848574975863UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_Bsq = {{(limb_t *)_blind_sig_com_d64_Bsq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_scM1_limbs[] = {7394294622012689099UL, 9825383902168072423UL, 2UL};
static const int_t _blind_sig_com_d64_scM1 = {{(limb_t *)_blind_sig_com_d64_scM1_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_scM2_limbs[] = {17541772227239051601UL, 15429691808631841182UL, 2UL};
static const int_t _blind_sig_com_d64_scM2 = {{(limb_t *)_blind_sig_com_d64_scM2_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_scM3_limbs[] = {13956427663845753597UL, 796498565867730010UL, 1UL};
static const int_t _blind_sig_com_d64_scM3 = {{(limb_t *)_blind_sig_com_d64_scM3_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_scM4_limbs[] = {2518408978183153514UL, 787616562185143506UL, 1UL};
static const int_t _blind_sig_com_d64_scM4 = {{(limb_t *)_blind_sig_com_d64_scM4_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_stdev1sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev1sq = {{(limb_t *)_blind_sig_com_d64_stdev1sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev2sq = {{(limb_t *)_blind_sig_com_d64_stdev2sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_stdev3sq_limbs[] = {10076815UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev3sq = {{(limb_t *)_blind_sig_com_d64_stdev3sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_stdev4sq_limbs[] = {165098542858UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev4sq = {{(limb_t *)_blind_sig_com_d64_stdev4sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_inv2_limbs[] = {598UL, 512UL};
static const int_t _blind_sig_com_d64_inv2 = {{(limb_t *)_blind_sig_com_d64_inv2_limbs, 2, 1}};
static const limb_t _blind_sig_com_d64_inv4_limbs[] = {299UL, 256UL};
static const int_t _blind_sig_com_d64_inv4 = {{(limb_t *)_blind_sig_com_d64_inv4_limbs, 2, 1}};
static const unsigned int _blind_sig_com_d64_n[2] = {2, 2};
static const limb_t _blind_sig_com_d64_Bz3sqr_limbs[] = {6938266263UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_Bz3sqr = {{(limb_t *)_blind_sig_com_d64_Bz3sqr_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_Bz4_limbs[] = {6501171UL, 0UL};
static const int_t _blind_sig_com_d64_Bz4 = {{(limb_t *)_blind_sig_com_d64_Bz4_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Pmodq_limbs[] = {13300984180396847864UL, 177UL};
static const int_t _blind_sig_com_d64_Pmodq = {{(limb_t *)_blind_sig_com_d64_Pmodq_limbs, 2, 1}};
static const limb_t _blind_sig_com_d64_l2Bsq0_limbs[] = {16UL, 0UL};
static const int_t _blind_sig_com_d64_l2Bsq0 = {{(limb_t *)_blind_sig_com_d64_l2Bsq0_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_l2Bsq1_limbs[] = {2000UL, 0UL};
static const int_t _blind_sig_com_d64_l2Bsq1 = {{(limb_t *)_blind_sig_com_d64_l2Bsq1_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_0_limbs[] = {1158231788156596285UL, 304UL};
static const int_t _blind_sig_com_d64_Ppmodq_0 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_0_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_1_limbs[] = {3175772519420360810UL, 159UL};
static const int_t _blind_sig_com_d64_Ppmodq_1 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_1_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_2_limbs[] = {10083009794685236540UL, 348UL};
static const int_t _blind_sig_com_d64_Ppmodq_2 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_2_limbs, 2, 1}};
static const limb_t _blind_sig_com_d64_Ppmodq_3_limbs[] = {2878165447571274421UL, 390UL};
static const int_t _blind_sig_com_d64_Ppmodq_3 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_3_limbs, 2, 1}};
static const int_srcptr _blind_sig_com_d64_l2Bsq[] = {_blind_sig_com_d64_l2Bsq0, _blind_sig_com_d64_l2Bsq1};
static const int_srcptr _blind_sig_com_d64_Ppmodq[] = {_blind_sig_com_d64_Ppmodq_0, _blind_sig_com_d64_Ppmodq_1, _blind_sig_com_d64_Ppmodq_2, _blind_sig_com_d64_Ppmodq_3};
static const polyring_t _blind_sig_com_d64_ring = {{_blind_sig_com_d64_q, 64, 75, 6, moduli_d64, 4, _blind_sig_com_d64_Pmodq, _blind_sig_com_d64_Ppmodq, _blind_sig_com_d64_inv2}};
static const dcompress_params_t _blind_sig_com_d64_dcomp = {{ _blind_sig_com_d64_q, _blind_sig_com_d64_qminus1, _blind_sig_com_d64_m, _blind_sig_com_d64_mby2, _blind_sig_com_d64_gamma, _blind_sig_com_d64_gammaby2, _blind_sig_com_d64_pow2D, _blind_sig_com_d64_pow2Dby2, 9, 1, 57 }};
static const abdlop_params_t _blind_sig_com_d64_tbox = {{ _blind_sig_com_d64_ring, _blind_sig_com_d64_dcomp, 12, 67, 0, 11, 9, _blind_sig_com_d64_Bsq, 1, 8, 5, 140, 1, 16, _blind_sig_com_d64_scM1, _blind_sig_com_d64_stdev1sq, 2, 12, _blind_sig_com_d64_scM2, _blind_sig_com_d64_stdev2sq}};
static const abdlop_params_t _blind_sig_com_d64_quad_eval_ = {{ _blind_sig_com_d64_ring, _blind_sig_com_d64_dcomp, 12, 67, 9, 2, 9, _blind_sig_com_d64_Bsq, 1, 8, 5, 140, 1, 16, _blind_sig_com_d64_scM1, _blind_sig_com_d64_stdev1sq, 2, 12, _blind_sig_com_d64_scM2, _blind_sig_com_d64_stdev2sq}};
static const abdlop_params_t _blind_sig_com_d64_quad_many_ = {{ _blind_sig_com_d64_ring, _blind_sig_com_d64_dcomp, 12, 67, 10, 1, 9, _blind_sig_com_d64_Bsq, 1, 8, 5, 140, 1, 16, _blind_sig_com_d64_scM1, _blind_sig_com_d64_stdev1sq, 2, 12, _blind_sig_com_d64_scM2, _blind_sig_com_d64_stdev2sq}};
static const lnp_quad_eval_params_t _blind_sig_com_d64_quad_eval = {{ _blind_sig_com_d64_quad_eval_, _blind_sig_com_d64_quad_many_, 2}};
static const lnp_tbox_params_t _blind_sig_com_d64 = {{ _blind_sig_com_d64_tbox, _blind_sig_com_d64_quad_eval, 6, _blind_sig_com_d64_n, 1, 2, 12, 2, 11, _blind_sig_com_d64_scM3, _blind_sig_com_d64_stdev3sq, 2, 18, _blind_sig_com_d64_scM4, _blind_sig_com_d64_stdev4sq, _blind_sig_com_d64_Bz3sqr, _blind_sig_com_d64_Bz4, &_blind_sig_com_d64_l2Bsq[0], _blind_sig_com_d64_inv4, 22682UL }};

static const unsigned int blind_sig_com_d64_Ps[6] = {4, 5, 6, 7, 8, 9};
static const unsigned int blind_sig_com_d64_Es0[2] = {0, 1};
static const unsigned int blind_sig_com_d64_Es1[2] = {2, 3};
static const unsigned int *blind_sig_com_d64_Es[2] = { blind_sig_com_d64_Es0, blind_sig_com_d64_Es1, };
static const unsigned int blind_sig_com_d64_Es_nrows[2] = {2, 2};

static const limb_t blind_sig_com_d64_p_limbs[] = {281474976711349UL};
static const int_t blind_sig_com_d64_p = {{(limb_t *)blind_sig_com_d64_p_limbs, 1, 0}};
static const limb_t blind_sig_com_d64_pinv_limbs[] = {15501319141652539544UL, 336UL};
static const int_t blind_sig_com_d64_pinv = {{(limb_t *)blind_sig_com_d64_pinv_limbs, 2, 0}};
static const unsigned int blind_sig_com_d64_s1_indices[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const lin_params_t blind_sig_com_d64 = {{ _blind_sig_com_d64, 64, blind_sig_com_d64_p, blind_sig_com_d64_pinv, 1, blind_sig_com_d64_s1_indices, 10, NULL, 0,  blind_sig_com_d64_Ps, 6, blind_sig_com_d64_Es, blind_sig_com_d64_Es_nrows, NULL, NULL }};

