// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(53,19,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(8,82,2^(32.9954))
// 
// Ring
// degree d = 64
// modulus q = 19342813113834066795298861, log(q) ~ 84.0
// factors q = q1
// 
// Compression
// D = 6
// gamma = 514062, log(gamma) ~ 18.971583
// 
// Dimensions of secrets
// s1: m1 = 10
// m: l = 0
// s2: m2 = 72
// 
// Size of secrets
// l2(s1) <= alpha = 49.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 6)
// exact euclidean: yes (dimensions: [2, 2], bounds: [4.0, 44.72136])
// approximate infinity: yes (psi: 2148.6388, dimension: 1, bound: 6400.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3174.4, log(stdev3/1.55) = 11.0
// stdev4 = 406323.2, log(stdev4/1.55) = 18.0
// 
// Repetition rate
// M1 = 2.5326351
// M2 = 3.0659392
// M3 = 1.0431783
// M4 = 1.0426968
// total = 8.4460322
// 
// Security
// MSIS dimension: 8
// MSIS root hermite factor: 1.0043962
// MLWE dimension: 53
// MLWE root hermite factor: 1.0043396
// 
// Proof size
// ~ 24.1171875000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241]
// bit length of products: [49, 99, 149, 199]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893]

#include "lazer.h"
static const limb_t _blind_sig_com_d64_q_limbs[] = {45UL, 1048576UL};
static const int_t _blind_sig_com_d64_q = {{(limb_t *)_blind_sig_com_d64_q_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_qminus1_limbs[] = {44UL, 1048576UL};
static const int_t _blind_sig_com_d64_qminus1 = {{(limb_t *)_blind_sig_com_d64_qminus1_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_m_limbs[] = {733905267838330298UL, 2UL};
static const int_t _blind_sig_com_d64_m = {{(limb_t *)_blind_sig_com_d64_m_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_mby2_limbs[] = {366952633919165149UL, 1UL};
static const int_t _blind_sig_com_d64_mby2 = {{(limb_t *)_blind_sig_com_d64_mby2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_gamma_limbs[] = {514062UL, 0UL};
static const int_t _blind_sig_com_d64_gamma = {{(limb_t *)_blind_sig_com_d64_gamma_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_gammaby2_limbs[] = {257031UL, 0UL};
static const int_t _blind_sig_com_d64_gammaby2 = {{(limb_t *)_blind_sig_com_d64_gammaby2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_pow2D_limbs[] = {64UL, 0UL};
static const int_t _blind_sig_com_d64_pow2D = {{(limb_t *)_blind_sig_com_d64_pow2D_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_pow2Dby2_limbs[] = {32UL, 0UL};
static const int_t _blind_sig_com_d64_pow2Dby2 = {{(limb_t *)_blind_sig_com_d64_pow2Dby2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Bsq_limbs[] = {42599160619254UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_Bsq = {{(limb_t *)_blind_sig_com_d64_Bsq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_scM1_limbs[] = {7394294622012689099UL, 9825383902168072423UL, 2UL};
static const int_t _blind_sig_com_d64_scM1 = {{(limb_t *)_blind_sig_com_d64_scM1_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_scM2_limbs[] = {1820084920535769461UL, 1216364161194770729UL, 3UL};
static const int_t _blind_sig_com_d64_scM2 = {{(limb_t *)_blind_sig_com_d64_scM2_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_scM3_limbs[] = {13956427663845753597UL, 796498565867730010UL, 1UL};
static const int_t _blind_sig_com_d64_scM3 = {{(limb_t *)_blind_sig_com_d64_scM3_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_scM4_limbs[] = {13220586277496944162UL, 787616562185149214UL, 1UL};
static const int_t _blind_sig_com_d64_scM4 = {{(limb_t *)_blind_sig_com_d64_scM4_limbs, 3, 0}};
static const limb_t _blind_sig_com_d64_stdev1sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev1sq = {{(limb_t *)_blind_sig_com_d64_stdev1sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev2sq = {{(limb_t *)_blind_sig_com_d64_stdev2sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_stdev3sq_limbs[] = {10076815UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev3sq = {{(limb_t *)_blind_sig_com_d64_stdev3sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_stdev4sq_limbs[] = {165098542858UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_stdev4sq = {{(limb_t *)_blind_sig_com_d64_stdev4sq_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_inv2_limbs[] = {22UL, 524288UL};
static const int_t _blind_sig_com_d64_inv2 = {{(limb_t *)_blind_sig_com_d64_inv2_limbs, 2, 1}};
static const limb_t _blind_sig_com_d64_inv4_limbs[] = {11UL, 262144UL};
static const int_t _blind_sig_com_d64_inv4 = {{(limb_t *)_blind_sig_com_d64_inv4_limbs, 2, 1}};
static const unsigned int _blind_sig_com_d64_n[2] = {2, 2};
static const limb_t _blind_sig_com_d64_Bz3sqr_limbs[] = {6938266263UL, 0UL, 0UL, 0UL};
static const int_t _blind_sig_com_d64_Bz3sqr = {{(limb_t *)_blind_sig_com_d64_Bz3sqr_limbs, 4, 0}};
static const limb_t _blind_sig_com_d64_Bz4_limbs[] = {6501171UL, 0UL};
static const int_t _blind_sig_com_d64_Bz4 = {{(limb_t *)_blind_sig_com_d64_Bz4_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Pmodq_limbs[] = {4904284587906064140UL, 144161UL};
static const int_t _blind_sig_com_d64_Pmodq = {{(limb_t *)_blind_sig_com_d64_Pmodq_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_l2Bsq0_limbs[] = {16UL, 0UL};
static const int_t _blind_sig_com_d64_l2Bsq0 = {{(limb_t *)_blind_sig_com_d64_l2Bsq0_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_l2Bsq1_limbs[] = {2000UL, 0UL};
static const int_t _blind_sig_com_d64_l2Bsq1 = {{(limb_t *)_blind_sig_com_d64_l2Bsq1_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_0_limbs[] = {1156299055576736257UL, 8316UL};
static const int_t _blind_sig_com_d64_Ppmodq_0 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_0_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_1_limbs[] = {3173911759260034433UL, 7147UL};
static const int_t _blind_sig_com_d64_Ppmodq_1 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_1_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_2_limbs[] = {8362058590799933057UL, 4591UL};
static const int_t _blind_sig_com_d64_Ppmodq_2 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_2_limbs, 2, 0}};
static const limb_t _blind_sig_com_d64_Ppmodq_3_limbs[] = {15567818015819406081UL, 1477UL};
static const int_t _blind_sig_com_d64_Ppmodq_3 = {{(limb_t *)_blind_sig_com_d64_Ppmodq_3_limbs, 2, 0}};
static const int_srcptr _blind_sig_com_d64_l2Bsq[] = {_blind_sig_com_d64_l2Bsq0, _blind_sig_com_d64_l2Bsq1};
static const int_srcptr _blind_sig_com_d64_Ppmodq[] = {_blind_sig_com_d64_Ppmodq_0, _blind_sig_com_d64_Ppmodq_1, _blind_sig_com_d64_Ppmodq_2, _blind_sig_com_d64_Ppmodq_3};
static const polyring_t _blind_sig_com_d64_ring = {{_blind_sig_com_d64_q, 64, 85, 6, moduli_d64, 4, _blind_sig_com_d64_Pmodq, _blind_sig_com_d64_Ppmodq, _blind_sig_com_d64_inv2}};
static const dcompress_params_t _blind_sig_com_d64_dcomp = {{ _blind_sig_com_d64_q, _blind_sig_com_d64_qminus1, _blind_sig_com_d64_m, _blind_sig_com_d64_mby2, _blind_sig_com_d64_gamma, _blind_sig_com_d64_gammaby2, _blind_sig_com_d64_pow2D, _blind_sig_com_d64_pow2Dby2, 6, 0, 66 }};
static const abdlop_params_t _blind_sig_com_d64_tbox = {{ _blind_sig_com_d64_ring, _blind_sig_com_d64_dcomp, 12, 72, 0, 11, 8, _blind_sig_com_d64_Bsq, 1, 8, 5, 140, 1, 16, _blind_sig_com_d64_scM1, _blind_sig_com_d64_stdev1sq, 2, 12, _blind_sig_com_d64_scM2, _blind_sig_com_d64_stdev2sq}};
static const abdlop_params_t _blind_sig_com_d64_quad_eval_ = {{ _blind_sig_com_d64_ring, _blind_sig_com_d64_dcomp, 12, 72, 9, 2, 8, _blind_sig_com_d64_Bsq, 1, 8, 5, 140, 1, 16, _blind_sig_com_d64_scM1, _blind_sig_com_d64_stdev1sq, 2, 12, _blind_sig_com_d64_scM2, _blind_sig_com_d64_stdev2sq}};
static const abdlop_params_t _blind_sig_com_d64_quad_many_ = {{ _blind_sig_com_d64_ring, _blind_sig_com_d64_dcomp, 12, 72, 10, 1, 8, _blind_sig_com_d64_Bsq, 1, 8, 5, 140, 1, 16, _blind_sig_com_d64_scM1, _blind_sig_com_d64_stdev1sq, 2, 12, _blind_sig_com_d64_scM2, _blind_sig_com_d64_stdev2sq}};
static const lnp_quad_eval_params_t _blind_sig_com_d64_quad_eval = {{ _blind_sig_com_d64_quad_eval_, _blind_sig_com_d64_quad_many_, 2}};
static const lnp_tbox_params_t _blind_sig_com_d64 = {{ _blind_sig_com_d64_tbox, _blind_sig_com_d64_quad_eval, 6, _blind_sig_com_d64_n, 1, 2, 12, 2, 11, _blind_sig_com_d64_scM3, _blind_sig_com_d64_stdev3sq, 2, 18, _blind_sig_com_d64_scM4, _blind_sig_com_d64_stdev4sq, _blind_sig_com_d64_Bz3sqr, _blind_sig_com_d64_Bz4, &_blind_sig_com_d64_l2Bsq[0], _blind_sig_com_d64_inv4, 24696UL }};

static const unsigned int blind_sig_com_d64_Ps[6] = {4, 5, 6, 7, 8, 9};
static const unsigned int blind_sig_com_d64_Es0[2] = {0, 1};
static const unsigned int blind_sig_com_d64_Es1[2] = {2, 3};
static const unsigned int *blind_sig_com_d64_Es[2] = { blind_sig_com_d64_Es0, blind_sig_com_d64_Es1, };
static const unsigned int blind_sig_com_d64_Es_nrows[2] = {2, 2};

static const limb_t blind_sig_com_d64_p_limbs[] = {288230376151713349UL};
static const int_t blind_sig_com_d64_p = {{(limb_t *)blind_sig_com_d64_p_limbs, 1, 0}};
static const limb_t blind_sig_com_d64_pinv_limbs[] = {5987292176225813849UL, 489594UL};
static const int_t blind_sig_com_d64_pinv = {{(limb_t *)blind_sig_com_d64_pinv_limbs, 2, 1}};
static const unsigned int blind_sig_com_d64_s1_indices[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const lin_params_t blind_sig_com_d64 = {{ _blind_sig_com_d64, 64, blind_sig_com_d64_p, blind_sig_com_d64_pinv, 1, blind_sig_com_d64_s1_indices, 10, NULL, 0,  blind_sig_com_d64_Ps, 6, blind_sig_com_d64_Es, blind_sig_com_d64_Es_nrows, NULL, NULL }};

